version: "3.9"

services:
  backend:
    build:
      context: ./backendproject
      dockerfile: Dockerfile
    image: backend-project:v1
    env_file:
      - ./backendproject/.env
    ports:
      - "8000:8000"
    command:  sh -c "chmod +x /app/migrate.sh && sh /app/migrate.sh && /app/entrypoint.sh"
    depends_on:
      - postgres_db

  postgres_db:
    container_name: postgres_db
    image: postgres:13-alpine
    restart: always
    command: -p 5434
    env_file:
      - ./backendproject/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5434
    ports:
      - "5434:5434"

  redis_db:
    image: redis
    expose:
      - 6388
    restart: always
    volumes:
      - redis_data:/data
    entrypoint: redis-server --appendonly yes --port 6388
    ports:
      - "6388:6388"
volumes:
  postgres_data:
  redis_data: